resources:
  - name: connecting_resource
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
      
  - name: ns_dockerbuild_gitRepo
    type: GitRepo
    configuration:
      path: vishnurao12/sample-script
      gitProvider: git_v
      branches: 
        include: master
        
#   - name: res_bundle
#     type: ReleaseBundle
#     configuration:
#       sourceDistribution: distribution_v
#       name: test_123
#       version: v1.0.1
      
  - name: sig_bundle
    type: ReleaseBundle
    configuration:
      sourceDistribution: distribution_v
      name: test_123
      version: v1.0.1
      
  - name: ns_promotedInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: master_test_promotedInfo
      buildNumber: 1

  - name: ns_buildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: master_test_buildInfo
      buildNumber: 1514


pipelines:
  - name: docker_push

    steps:
      - name: To_build_Docker_Image
        type: DockerBuild
        configuration:
          affinityGroup: "BasicTest"
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: u18.jfrog-pipelines.com/:8082/docker-local/node

          dockerImageTag: latest
          integrations:
            - name: art_v

          inputResources:
            - name: ns_dockerbuild_gitRepo 
            - name: connecting_resource


      - name: To_Push_Docker_Image
        type: DockerPush
        configuration:
          affinityGroup: "BasicTest"
          autoPublishBuildInfo: false 
          targetRepository: docker-local #required
          integrations:
            - name: art_v 
          inputSteps:
            - name: To_build_Docker_Image
            
               
      - name: To_publish_buildInfo 
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: To_Push_Docker_Image
          outputResources:
            - name: ns_buildInfo

      - name: To_promote_build
        type: PromoteBuild
        configuration:
          targetRepository: test-generic-local
          integrations:
            - name: art_v
          inputResources:
            - name: ns_buildInfo
          inputSteps:
            - name: To_publish_buildInfo
          outputResources:
            - name: ns_promotedInfo

#       - name: docker_releaseBundle
#         type: CreateReleaseBundle
#         configuration:
#           #inherits from bash
#           releaseBundleName:        test_123
#           releaseBundleVersion:     v1.0.1
#           inputResources:
#             - name: ns_promotedInfo
#           outputResources:
#             - name: res_bundle
#           dryRun: false
          
#       - name: docker_sign_releaseBundle
#         type: SignReleaseBundle
#         configuration:
#           inputResources:
#             - name:            res_bundle
#           outputResources:
#             - name:            sig_bundle
