pipelines:
  - name: sample1
    steps:
      - name: testBash1
        type: Bash       
        execution:
          onExecute:
            - mkdir testKey
            - cd testKey
            - |
              cat >keyConf <<EOF
                   %echo Generating a basic OpenPGP key
                   Key-Type: RSA
                   Key-Length: 2048
                   Name-Real: jfrog pipelines
                   Name-Comment: e2e
                   Name-Email: jfrogAutomation@jfrog.com
                   Expire-Date: 0
                   %no-protection
                   # Do a commit here, so that we can later print "done" :-)
                   %commit
                   %echo done
                   EOF
            - cat keyConf
            - gpg --verbose --batch --gen-key keyConf
