pipelines:
  - name: sample1
    configuration:
      environmentVariables:
        wow: test
        server: severname
    steps:
      - name: testBash1
        type: Bash       
        execution:
          onExecute:
            - rm -rf testKey | true
            - mkdir testKey
            - cd testKey
            - |
              cat >keyConf <<EOF
                   %echo Generating a basic OpenPGP key
                   Key-Type: RSA
                   Key-Length: 2048
                   Name-Real: jfrog pipelines
                   Name-Comment: e2e
                   Name-Email: jfrogAutomation@jfrog.com
                   Expire-Date: 0
                   %no-protection
                   # Do a commit here, so that we can later print "done" :-)
                   %commit
                   %echo done
              EOF
            - cat keyConf
            - gpg --verbose --batch --gen-key keyConf
            - gpg --output pri.key --armor --export-secret-keys jfrogAutomation@jfrog.com
            - cat pri.key
            - gpg --output pub.key --armor --export jfrogAutomation@jfrog.com
            - cat pub.key
            - echo $wow
            - echo $severname
            - curl -uadmin:$wow -H "Accept: application/json" -H "Content-Type: application/json" -X POST "https://`$severname`.jfrogdev.org/distribution/api/v1/keys/gpg" -T gpg.json -Lvvv
