resources:
  - name:       propertyBag
    type:       PropertyBag
    configuration:
      test: test
      
  - name: resource_pipelines128
    type: GitRepo
    configuration:
     gitProvider: git_v
     path: vishnurao12/pipelines
     files: 
       include: ^README.md$
     branches:
       include: ^{{gitBranch}}$
     buildOn:
       pullRequestCreate: true
     cancelPendingRunsOn:
       pullRequestUpdate: true
     runtime:
       type: host
pipelines:
  - name: Pipelines_matrixtest
    steps:
      - name: PreMatrix_step
        type: PreMatrix
        configuration:
          inputResources:
            - name: propertyBag
            - name: resource_pipelines128
        execution:
          onStart:
            - pushd $res_resource_pipelines128_resourcePath
            - ls
            
            
      - name: Matrix_test
        type: Matrix
        stepMode: Bash
        configuration:
          inputSteps: 
            - name: PreMatrix_step  
        stepletMultipliers:
          environmentVariables:
            - delay: 1
                
        execution:
          onExecute:
            - echo "I am on matrix step"
            - printenv
            - pwd
            - ls
            - cd /
            - ls
#             - |
#               [ $fail == 'false' ] 
