
resources:
 - name: resource_pipelines12
   type: GitRepo
   configuration:
     gitProvider: git_v
     path: vishnurao12/pipelines
     files: 
       include: ^README.md$
pipelines:
  - name: mulitnode
    steps:
      - name: myStep123
        type: Bash
        configuration:
#           timeoutSeconds: 7200
#           timeoutSeconds: 60
          environmentVariables:
            testCases: setup.js
#           runtime:           
#             type: host
          inputResources: 
            - name: resource_pipelines12
          integrations:
            - name: git_v
#            - name: art_v
        execution:
          onExecute:
#             - docker images
            - echo 'hi'
            - echo 'hi'
      - name: multinode
        type: Matrix
        stepMode: Bash
        configuration:
          multiNode: true
          inputSteps: 
            - name: myStep123
        stepletMultipliers:
          environmentVariables:
            - foo: "foo"
            - foo: "bar"
            - foo: "baz"
            - foo: "baz"
            - foo: "baz"
            - foo: "baz"
            - foo: "baz"
            - foo: "baz"
            - foo: "baz"
            - foo: "baz"
            - foo: "baz"
            - foo: "baz"
            - foo: "baz"
        execution:
          onExecute:
            - echo $foo
