pipelines:
  - name: Pipelines_matrixtest
    steps:
      - name: Matrix_test
        type: Matrix
        stepMode: Bash
        configuration:
          multiNode: true
          runtime:
            type: host
        stepletMultipliers:
          environmentVariables:
            - delay: 1
              fail: 'true'
            - delay: 10
              fail: 'true'
            - delay: 15
              fail: 'false'
            - delay: 20
              fail: 'false'
            - delay: 11
              fail: 'true'
            - delay: 101
              fail: 'true'
            - delay: 151
              fail: 'false'
            - delay: 201
              fail: 'false'
            - delay: 12
              fail: 'true'
            - delay: 102
              fail: 'true'
            - delay: 152
              fail: 'false'
            - delay: 202
              fail: 'false'
        execution:
          onExecute:
            - echo "I am on matrix step"
