pipelines:
  - name: testpipeline
    steps:
      - name: testStep
        type: Bash
        execution:
          onStart:
            - echo "executing onStart"
          onExecute:
            - echo "executing onExecute"
