resources:
  - name: connecting_resource_node_test
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2

pipelines:
  - name: node_test
    configuration:
      environmentVariables:
        readOnly:
          name: "vishnu"
    steps:
      - name: myStep112
        type: Bash
        configuration:
          outputResources: 
            - name: connecting_resource_node_test
#               trigger: false
          integrations:
            - name: git_v
            - name: art_v
        execution:
          onExecute:
            - echo automation > test.sh
            - echo automation > foo1
            - echo 'hi'
#             - jfrog rt u test.sh example-repo-local/setup/test.sh
#             - jfrog rt u foo1 example-repo-local/setup/foo1
            - write_output connecting_resource_node_test "test=value"

      - name: win_2019
        type: PowerShell
        configuration:
          nodePool: win_2019
          inputResources:
            - name: connecting_resource_node_test
          integrations:
            - name: git_v
            - name: art_v
        execution:
          onExecute:
            - write-output "Hi"
            - docker images
            - jfrog --version

      - name: c7dynamic
        type: Bash
        configuration:
          nodePool: c7dynamic
          inputResources:
            - name: connecting_resource_node_test
          integrations:
            - name: git_v
            - name: art_v
        execution:
          onExecute:
            - printenv
            - docker images
            - jfrog --version

      - name: u18dynamic
        type: Bash
        configuration:
          nodePool: u18dynamic
          inputResources:
            - name: connecting_resource_node_test
          integrations:
            - name: git_v
            - name: art_v
        execution:
          onExecute:
            - printenv
            - docker images
            - jfrog --version

#       - name: rhel
#         type: Bash
#         configuration:
#           nodePool: rhe7
#           inputResources:
#             - name: connecting_resource_node_test
#         execution:
#           onExecute:
#             - printenv
            
      - name: u20dynamic
        type: Bash
        configuration:
          nodePool: u20dynamic
          inputResources:
            - name: connecting_resource_node_test
          integrations:
            - name: git_v
            - name: art_v
        execution:
          onExecute:
            - printenv
            - docker images
            - jfrog --version
            
      - name: c8dynamic
        type: Bash
        configuration:
          nodePool: c8dynamic
          inputResources:
            - name: connecting_resource_node_test
          integrations:
            - name: git_v
            - name: art_v
        execution:
          onExecute:
            - printenv
            - docker images
            - jfrog --version

#       - name: win_2019
#         type: PowerShell
#         configuration:
#           nodePool: win_2019
#           inputResources:
#             - name: connecting_resource_node_test
#         execution:
#           onExecute:
#             - write-output "Hi"
#             - docker images

#       - name: u16
#         type: Bash
#         configuration:
#           nodePool: u16
#           inputResources:
#             - name: connecting_resource
#         execution:
#           onExecute:
#             - printenv

#       - name: c7node
#         type: Bash
#         configuration:
#           nodePool: c7node
#           inputResources:
#             - name: connecting_resource
#         execution:
#           onExecute:
#             - printenv

#       - name: u18
#         type: Bash
#         configuration:
#           nodePool: u18
#           inputResources:
#             - name: connecting_resource
#         execution:
#           onExecute:
#             - printenv

#       - name: rhel
#         type: Bash
#         configuration:
#           nodePool: rhel
#           inputResources:
#             - name: connecting_resource
#         execution:
#           onExecute:
#             - printenv
