#resources 
resources:
  - name: EY_PenTest_gitRepo
    type: GitRepo
    configuration:
      gitProvider: GitHub_Integration
      path: vishnurao12/pipelines
      files: 
        include: ^README.md$
      branches:
        include: ^{{gitBranch}}$
#pipeline
pipelines:
  - name: EY_PenTest_Pipeline
#steps
    steps:
      - name: EY_PenTest_Step
        type: Bash
        configuration:
          inputResources: 
            - name: EY_PenTest_gitRepo
        execution:
          onExecute:
            - echo 'hi'
            



      
