resources:
  - name: repo_git
    type: GitRepo
    configuration:
      path: vishnurao12/pipelines
      gitProvider: git_v
      
      buildOn:
        commit: false
        pullRequestCreate: true
        pullRequestClose: true
  - name: repo_git_commit
    type: GitRepo
    configuration:
      path: vishnurao12/pipelines
      gitProvider: git_v
      buildOn:
        commit: true
        
  - name: repo_git_false
    type: GitRepo
    configuration:
      path: vishnurao12/pipelines
      gitProvider: git_v
      buildOn:
        pullRequestCreate: false

pipelines:
  - name: test
    steps:
      - name: test
        type: Bash
        configuration:
          inputResources:
            - name: repo_git
              trigger: true
        execution:
          onExecute:
            - printenv  
  - name: test1
    steps:
      - name: test1
        type: Bash
        configuration:
          inputResources:
            - name: repo_git_commit
              trigger: true
        execution:
          onExecute:
            - printenv
  - name: test2
    steps:
      - name: test2
        type: Bash
        configuration:
          inputResources:
            - name: repo_git_false
              trigger: true
        execution:
          onExecute:
            - printenv


      
