# resources:
#  - name: resource_pipelines1245
#    type: GitRepo
#    configuration:
#      gitProvider: git_v
#      path: vishnurao12/pipelines
#      files: 
#        include: ^README.md$
#      branches:
#        include: ^{{gitBranch}}$
# #      buildOn:
# #        pullRequestCreate: true
# #      cancelPendingRunsOn:
# #        pullRequestUpdate: true

# pipelines:
#   - name: testing_123
#     steps:
#       - name: myStep112
#         type: Bash
#         configuration:
#          environmentVariables:
#            testCases: setup.js
          
#          inputResources: 
#            - name: resource_pipelines1245
#          integrations:
#            - name: git_v
#         execution:
#           onExecute:
#             - printenv | grep "testCases"
#             - echo $testCases
#             - testcaseDup="[\"core/testHarness/$testCases\"]"
#             - echo $testcaseDup
#             - pushd $res_resource_pipelines1245_resourcePath
#             - ls
#             - echo "hi"
#           onSuccess:
#             - pushd $res_resource_pipelines1245_resourcePath
#             - ls

pipelines:
  - name: testing_123
    steps:
      - name: myStep112
        type: Bash
        configuration:
#           nodePool: u16test
#           timeoutSeconds: 7200
#           timeoutSeconds: 60
          environmentVariables:
            testCases: 'setup.js'
#           runtime:           
#             type: host
#           inputResources: 
#             - name: resource_pipelines1245
#             - name: resource_pipelines3421
#             - name: resource_pipelines155
          integrations:
            - name: git_v
            - name: art_v
        execution:
          onStart:
#             - jfrog rt repo-delete helm-generic || true
#             - jfrog rt repo-delete docker-test-local || true
              - env
              - printenv


      
