# resources:
#  - name: gitResource
#    type: GitRepo
#    configuration:
#      gitProvider: git_v
#      path: vishnurao12/pipelines
#      branches:
#        include:    master
# pipelines:
#   - name: pipelines_test
#     configuration:
#       nodePool: gcp-test
#     steps:
#       - name: myStep1
#         type: Bash
#         configuration: 
#          nodePool: gcp-test
#          inputResources: # optional
#            - name: gitResource
#              trigger: true
#         execution:
#           onExecute:
#             - printenv

#       - name: myStep2
#         type: Bash
#         configuration: 
#           nodePool: gcp-test
#           inputResources: # optional
#             - name: gitResource
#               trigger: true
#           inputSteps: 
#             - name: myStep1
#         execution:
#           onExecute:
#             - printenv

#       - name: myStep3
#         type: Bash
#         configuration: 
#           nodePool: gcp-test
#           inputResources: # optional
#             - name: gitResource
#               trigger: true
#           inputSteps: 
#             - name: myStep2
#         execution:
#           onExecute:
#             - printenv

resources:
 - name: resource_pipelines1245
   type: GitRepo
   configuration:
     gitProvider: git_v
     path: vishnurao12/pipelines
     files: 
       include: ^README.md$
     branches:
       include: ^test2$
#      buildOn:
#        pullRequestCreate: true
#      cancelPendingRunsOn:
#        pullRequestUpdate: true

pipelines:
  - name: testing_123
    steps:
      - name: myStep112
        type: Bash
        configuration:
          inputResources: 
            - name: resource_pipelines1245
          integrations:
            - name: git_v
        execution:
          onExecute:
            - printenv
            - pushd $res_resource_pipelines1245_resourcePath
            - ls
            - sleep 15m
            

      - name: myStep1121
        type: Bash
        configuration:
          inputResources: 
            - name: resource_pipelines1245
          inputSteps:
            - name:  myStep112
          integrations:
            - name: git_v
        execution:
          onExecute:
            - sleep 15m
            - ls
            
      - name: myStep1122
        type: Bash
        configuration:
          inputResources: 
            - name: resource_pipelines1245
          inputSteps:
            - name:  myStep1121
          integrations:
            - name: git_v
        execution:
          onExecute:
            - sleep 15m
            - ls
            
      - name: matrix
        type: Matrix
        stepletMultipliers:
          environmentVariables:
            - foo: bar
            - boo: foo
        configuration:
        
          multiNode: true
          runtime:
            type: host
        execution:
          onExecute:
            - printenv
            - echo lol
            - echo loool
            
      - name: myStep121
        type: Bash
        configuration:
          affinityGroup: group1
          inputResources: 
           - name: resource_pipelines1245
          integrations:
            - name: git_v
        execution:
          onExecute:
            - printenv
            - pushd $res_resource_pipelines1245_resourcePath
            - ls
            - sleep 5m
            
      - name: myStep122
        type: Bash
        configuration:
          affinityGroup: group1
          integrations:
            - name: git_v
          inputSteps:
            - name: myStep121
        execution:
          onExecute:
            - printenv
            - pushd $res_resource_pipelines1245_resourcePath
            - ls
            - sleep 5m
 
      - name: myStep123
        type: Bash
        configuration:
          affinityGroup: group1
          integrations:
            - name: git_v
          inputSteps:
            - name: myStep122
        execution:
          onExecute:
            - printenv
            - pushd $res_resource_pipelines1245_resourcePath
            - ls
            - sleep 5m
            
      - name: myStep124
        type: Bash
        configuration:
          affinityGroup: group1
          integrations:
            - name: git_v
          inputSteps:
            - name: myStep123
        execution:
          onExecute:
            - printenv
            - pushd $res_resource_pipelines1245_resourcePath
            - ls
            - sleep 5m
            
      - name: myStep125
        type: Bash
        configuration:
          affinityGroup: group1
          integrations:
            - name: git_v
          inputSteps:
            - name: myStep124
        execution:
          onExecute:
            - printenv
            - pushd $res_resource_pipelines1245_resourcePath
            - ls
            - sleep 5m
            
      - name: myStep126
        type: Bash
        configuration:
          affinityGroup: group1
          integrations:
            - name: git_v
          inputSteps:
            - name: myStep125
        execution:
          onExecute:
            - printenv
            - pushd $res_resource_pipelines1245_resourcePath
            - ls
            
      - name: myStep127
        type: Bash
        configuration:
          affinityGroup: group1
          integrations:
            - name: git_v
          inputSteps:
            - name: myStep126
        execution:
          onExecute:
            - printenv
            - pushd $res_resource_pipelines1245_resourcePath
            - ls
            - sleep 5m
            
