pipelines:
  - name: testJenkins
    configuration:
      nodePool: u16dynamic
    steps:
      - name: testStepJenkins
        type: Jenkins
        configuration:
          jenkinsJobName: testPipeline     
          buildParameters:
            foo1: bar1
            foo2: bar2  
          integrations:
            - name: jenkins
        
